**EXERCICI 1**

In [28]:
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()
iris.data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [27]:
iris.target[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**EXERCICI 2**

In [15]:
iris_data_target = np.concatenate((iris.data, iris.target.reshape(-1, 1)), axis=1)
print(iris_data_target[:5])

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


**EXERCICI 3**

Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") i la longitud del pètal ("petal length (cm)"). Mostra els resultats amb dos decimals.

In [29]:
sepal_mitjana = np.mean(iris.data[:, 0])
sepal_desviacio = np.std(iris.data[:, 0])
petal_mitjana = np.mean(iris.data[:, 2])
petal_desviacio = np.std(iris.data[:, 2])

# Display the results with two decimal places
print("Longitud Sepal  (cm) - Mitjana: {:.2f}, Desviació estàndar: {:.2f}".format(sepal_mitjana, sepal_desviacio))
print("Longitud Petal (cm) - Mitjana: {:.2f}, Desviació estàndar: {:.2f}".format(petal_mitjana, petal_desviacio))

Longitud Sepal  (cm) - Mitjana: 5.84, Desviació estàndar: 0.83
Longitud Petal (cm) - Mitjana: 3.76, Desviació estàndar: 1.76


**EXERCICI 4**

Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior. La utilitzaràs d'aquí endavant.

In [30]:
iris_data_target = np.concatenate((iris.data, iris.target.reshape(-1, 1)), axis=1)
random_sample = np.random.choice(iris_data_target.shape[0], size=20, replace=False)
sample_data_target = iris_data_target[random_sample]
sample_data_target

array([[5. , 3.2, 1.2, 0.2, 0. ],
       [6.1, 3. , 4.6, 1.4, 1. ],
       [4.4, 3.2, 1.3, 0.2, 0. ],
       [5.6, 2.8, 4.9, 2. , 2. ],
       [6.1, 2.8, 4. , 1.3, 1. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [5.5, 3.5, 1.3, 0.2, 0. ],
       [5.9, 3. , 4.2, 1.5, 1. ],
       [5.7, 2.5, 5. , 2. , 2. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [6.8, 3.2, 5.9, 2.3, 2. ],
       [6.1, 2.6, 5.6, 1.4, 2. ],
       [6.3, 2.3, 4.4, 1.3, 1. ],
       [7.2, 3. , 5.8, 1.6, 2. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [6.9, 3.1, 4.9, 1.5, 1. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.7, 3. , 4.2, 1.2, 1. ],
       [5.5, 2.3, 4. , 1.3, 1. ]])

**EXERCICI 5**

Crea una matriu que mostri:
*   La mitjana de cada característica per espècie.(mean)
*   La desviació estàndard de cada característica per espècie. (std)



In [41]:
iris_data_target.mean(axis=1)

array([2.04, 1.9 , 1.88, 1.88, 2.04, 2.28, 1.94, 2.02, 1.78, 1.92, 2.16,
       2.  , 1.86, 1.7 , 2.24, 2.4 , 2.2 , 2.06, 2.3 , 2.14, 2.14, 2.14,
       1.88, 2.12, 2.06, 1.96, 2.08, 2.08, 2.04, 1.94, 1.94, 2.14, 2.18,
       2.26, 1.94, 1.92, 2.1 , 2.  , 1.78, 2.04, 2.02, 1.68, 1.82, 2.14,
       2.24, 1.9 , 2.14, 1.88, 2.14, 1.98, 3.46, 3.32, 3.48, 2.82, 3.28,
       3.06, 3.38, 2.52, 3.28, 2.84, 2.5 , 3.12, 2.84, 3.22, 2.88, 3.32,
       3.12, 2.92, 3.08, 2.82, 3.34, 3.04, 3.24, 3.16, 3.18, 3.28, 3.36,
       3.48, 3.18, 2.76, 2.76, 2.72, 2.92, 3.28, 3.08, 3.3 , 3.4 , 3.06,
       3.  , 2.86, 2.94, 3.22, 2.92, 2.52, 2.96, 3.02, 3.02, 3.14, 2.54,
       2.98, 4.02, 3.5 , 4.02, 3.72, 3.9 , 4.26, 3.12, 4.06, 3.76, 4.28,
       3.76, 3.66, 3.88, 3.44, 3.62, 3.84, 3.76, 4.48, 4.3 , 3.34, 4.02,
       3.46, 4.24, 3.54, 3.96, 4.04, 3.52, 3.56, 3.78, 3.92, 4.04, 4.42,
       3.8 , 3.54, 3.54, 4.22, 3.94, 3.76, 3.52, 3.9 , 3.96, 3.88, 3.5 ,
       4.04, 4.04, 3.84, 3.54, 3.74, 3.86, 3.56])

In [42]:
iris_data_target.std(axis=1)

array([1.97240969, 1.84173831, 1.81041432, 1.75430898, 1.95714077,
       2.07016908, 1.78616908, 1.92083315, 1.66901168, 1.86804711,
       2.08863592, 1.8547237 , 1.82822318, 1.68878655, 2.28175371,
       2.25654603, 2.09857094, 1.95407267, 2.16610249, 1.99459269,
       2.03725305, 1.96020407, 1.87018716, 1.87445992, 1.84564352,
       1.86504692, 1.87872297, 1.99739831, 1.98957282, 1.79510445,
       1.81284307, 2.01156655, 2.11414285, 2.20689828, 1.84889156,
       1.91248529, 2.10618138, 1.9462785 , 1.68807583, 1.95202459,
       1.93018134, 1.62529997, 1.71860408, 1.85860162, 1.95611861,
       1.79108905, 2.00758561, 1.77358394, 2.05776578, 1.91248529,
       2.2105203 , 1.9792928 , 2.18760143, 1.70105849, 2.03509214,
       1.81394597, 1.9548913 , 1.47702404, 2.09895212, 1.56025639,
       1.54919334, 1.79041895, 1.92416216, 1.9405154 , 1.67020957,
       2.08365064, 1.74287119, 1.84975674, 1.96712989, 1.74745529,
       1.81945047, 1.87253838, 2.03528868, 1.98252364, 1.99939

**EXERCICI 6**

Calcula la quantitat de mostres per espècie.

Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"

```

```



In [46]:
especies = np.unique(iris_data_target[:, -1])
a=len(especies)
a

3

In [43]:
np.max(iris_data_target)

7.9

**EXERCICI 7**

Calcula la matriu de correlació entre les variables.

Filtra els valors majors a la mitjana (de l'exercici 3) de la longitud dels pètals i mostra-ho.

Troba la mostra amb els pètals més llargs.

In [47]:
np.corrcoef(iris_data_target)

array([[1.        , 0.99706483, 0.99997795, ..., 0.73911793, 0.73861621,
        0.72169879],
       [0.99706483, 1.        , 0.99750791, ..., 0.78062955, 0.77554908,
        0.76056628],
       [0.99997795, 0.99750791, 1.        , ..., 0.74245616, 0.74174869,
        0.72472528],
       ...,
       [0.73911793, 0.78062955, 0.74245616, ..., 1.        , 0.99295525,
        0.99565547],
       [0.73861621, 0.77554908, 0.74174869, ..., 0.99295525, 1.        ,
        0.99497962],
       [0.72169879, 0.76056628, 0.72472528, ..., 0.99565547, 0.99497962,
        1.        ]])

In [ ]:
iris_data_target = np.concatenate((iris.data, iris.target.reshape(-1, 1)), axis=1)
mitjana = np.mean(iris_data_target[:, 2])
a=iris_data_target[iris_data_target[:, 2] > mitjana]
a



In [58]:
iris_data_target = np.concatenate((iris.data, iris.target.reshape(-1, 1)), axis=1)
sorted_by_petal_length = iris_data_target[np.argsort(iris_data_target[:, 2])]
petals_llargs= sorted_by_petal_length[-5:]
